server:
  port: 5000
spring:
  application:
    name: dima-user-backend
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dima-db.cdw00ck0wa6r.eu-north-1.rds.amazonaws.com:5432/seriestime
    username: postgres
    password: 3H1OH3deGVR3SrQPObLx
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  h2:
    console:
      enabled: true
message: Hello from default profile