server:
  port: 5000
spring:
  application:
    name: dima-user-backend
  datasource:
    driverClassName: org.postgresql.Driver
    #Real credentials for the DB are hide for security and privacy issues
    url: jdbc:postgresql://localhost:5438/seriestime
    username: postgres
    password: postgres
  jpa:
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  h2:
    console:
      enabled: true
message: Hello from default profile