name: automatic

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test_with_gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test
        run: |
          chmod +x gradlew
          ./gradlew test --stacktrace

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down